name: Build APK

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Create dummy www
        run: |
          mkdir -p www
          echo "<h1>Loading...</h1>" > www/index.html

      - name: Init App
        run: npx cap init myapp com.myapp.app --web-dir=www || true

      - name: Add Android
        run: npx cap add android || true

      - name: Sync Android
        run: npx cap sync android

      - name: Add Internet Permission
        run: |
         sed -i '/<application/i <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        run: |
         cd android
         chmod +x gradlew
         ./gradlew assembleDebug
      - name: Check APK file
        run: find android -name "*.apk"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: my-apk
         path: android/app/build/outputs/apk/debug/*.apk
    
      
